apiVersion: v1
kind: ServiceAccount
metadata:
  name: edgelake-operator-controller-manager
  namespace: edgelake-operator-system
  labels:
    app.kubernetes.io/name: edgelake-operator
    app.kubernetes.io/managed-by: open-horizon
