apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: edgelake-operator-manager-rolebinding
  labels:
    app.kubernetes.io/name: edgelake-operator
    app.kubernetes.io/managed-by: open-horizon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edgelake-operator-manager-role
subjects:
  - kind: ServiceAccount
    name: edgelake-operator-controller-manager
    namespace: edgelake-operator-system
